#!/bin/sh

echo -e "--------------------------------------"
echo -e "folder:${PWD}"
echo -e "--------------------------------------"

if [ ! -d ".git" ]; then
  echo -e "\nNot a git repository!!!"
  exit 0
fi

echo -e "\n=> Processing git repository..."

echo -e "\n=> Stashing not commited changes..."
git stash save  --include-untracked "Saved changes in a stash"
git lfs prune
git gc --aggressive --force
echo -e "\n=> Deleting all files and folders..."
git rm -rf .
echo -e "\nDone.\n"

echo -e "To restore working directory content: git reset --hard HEAD"

